---
title: "rerun_acat"
author: "XSun"
date: "2023-12-06"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
---

```{r }
suppressMessages(library(ggplot2))
suppressMessages(library(gridExtra))
suppressMessages(library(tidyr))
suppressMessages(library(forcats))

celltypes <- c("B_cell","CD14_positive_monocyte","CD15_positive_leukocyte","platelet","T_cell","thymocyte")
type <- c("B cell (CD19+)","Monocyte (CD14+)","Leukocyte (CD15+)","Platelet","T cell (CD4+)","T cell (CD8+)")

```

# Real ACAT p-values

```{r}

folder_acat <- "/project/xinhe/xsun/pathway_factor/analysis/2.ACAT/results/"

p1 <- list()
for (i in 1:length(celltypes)) {
  
  file_acat <- paste0(folder_acat,celltypes[i],"_real_acat.rdata")
  load(file_acat)
  
  p <- as.data.frame(unlist(acat_celltype))
  colnames(p) <- "p"
  p1[[i]] <-  ggplot(p, aes(x=p)) + geom_histogram(breaks = seq(0, 1, by = 0.05),color="white",fill = "steelblue")+ 
    theme_bw(base_line_size =0.3) +
    ggtitle(type[i]) + theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "ACAT p-values from real data",
         y = "Count") +
    
    theme(axis.title.x = element_text(size = 14),
          axis.text.x = element_text(size = 12, color = "black"),
          axis.title.y = element_text(size = 14),
          axis.text.y = element_text(size = 12, color = "black"),
          text= element_text(family="Times")) 
  
  
}

all1 <- grid.arrange(p1[[1]],p1[[2]],p1[[3]],p1[[4]],p1[[5]],p1[[6]], nrow = 2)

p1 <- list()
for (i in 1:length(celltypes)) {
  
  file_acat <- paste0(folder_acat,celltypes[i],"_real_acat.rdata")
  load(file_acat)
  
  p <- as.data.frame(unlist(acat_celltype))
  colnames(p) <- "p"
  
  plotdata <- data.frame(observed = -log10(sort(as.numeric(as.character(p$p)))),
                       expected = -log10(ppoints(nrow(p))))
 

  p1[[i]] <- ggplot(plotdata) + theme_bw(base_line_size =0.3) +
    geom_point(aes(expected, observed), shape = 1, size = 1.5,color = "steelblue") +
    geom_abline(intercept = 0, slope = 1, alpha = 0.6, color = "red") +
    ggtitle(type[i]) + theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = expression(paste("Expected -log"[10],"(p-value)")),
       y = expression(paste("Observed -log"[10],"(p-value)"))) +
  
    theme(axis.title.x = element_text(size = 14),
        axis.text.x = element_text(size = 12, color = "black"),
        axis.title.y = element_text(size = 14),
        axis.text.y = element_text(size = 12, color = "black"),
        text= element_text(family="Times")) 
  
  
}

all1 <- grid.arrange(p1[[1]],p1[[2]],p1[[3]],p1[[4]],p1[[5]],p1[[6]], nrow = 2)

```


# corrected ACAT p-values

```{r}

folder_acat <- "/project/xinhe/xsun/pathway_factor/analysis/2.ACAT/results/"

p1 <- list()
for (i in 1:length(celltypes)) {
  
  file_acat <- paste0(folder_acat,celltypes[i],"_real_acat.rdata")
  load(file_acat)
  
  p <- as.data.frame(unlist(acat_celltype))
  colnames(p) <- "p"
  p1[[i]] <-  ggplot(p, aes(x=p)) + geom_histogram(breaks = seq(0, 1, by = 0.05),color="white",fill = "steelblue")+ 
    theme_bw(base_line_size =0.3) +
    ggtitle(type[i]) + theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = "ACAT p-values from real data",
         y = "Count") +
    
    theme(axis.title.x = element_text(size = 14),
          axis.text.x = element_text(size = 12, color = "black"),
          axis.title.y = element_text(size = 14),
          axis.text.y = element_text(size = 12, color = "black"),
          text= element_text(family="Times")) 
  
  
}

all1 <- grid.arrange(p1[[1]],p1[[2]],p1[[3]],p1[[4]],p1[[5]],p1[[6]], nrow = 2)

p1 <- list()
for (i in 1:length(celltypes)) {
  
  file_acat <- paste0(folder_acat,celltypes[i],"_real_acat.rdata")
  load(file_acat)
  
  p <- as.data.frame(unlist(acat_celltype))
  colnames(p) <- "p"
  
  plotdata <- data.frame(observed = -log10(sort(as.numeric(as.character(p$p)))),
                       expected = -log10(ppoints(nrow(p))))
 

  p1[[i]] <- ggplot(plotdata) + theme_bw(base_line_size =0.3) +
    geom_point(aes(expected, observed), shape = 1, size = 1.5,color = "steelblue") +
    geom_abline(intercept = 0, slope = 1, alpha = 0.6, color = "red") +
    ggtitle(type[i]) + theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = expression(paste("Expected -log"[10],"(p-value)")),
       y = expression(paste("Observed -log"[10],"(p-value)"))) +
  
    theme(axis.title.x = element_text(size = 14),
        axis.text.x = element_text(size = 12, color = "black"),
        axis.title.y = element_text(size = 14),
        axis.text.y = element_text(size = 12, color = "black"),
        text= element_text(family="Times")) 
  
  
}

all1 <- grid.arrange(p1[[1]],p1[[2]],p1[[3]],p1[[4]],p1[[5]],p1[[6]], nrow = 2)

```


