---
title: "Number of Instrument Variables"
author: "XSun"
date: "2025-10-08"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
---

| Full Trait Name                                         | Abbr.   | Category                         |
|---------------------------------------------------------|---------|----------------------------------|
| Crohn’s disease                                         | CD      | Immune / Inflammatory disease    |
| Inflammatory bowel disease                              | IBD     | Immune / Inflammatory disease    |
| Rheumatoid arthritis                                    | RA      | Immune / Inflammatory disease    |
| Ulcerative colitis                                      | UC      | Immune / Inflammatory disease    |
| Atopic dermatitis                                       | ATD     | Immune / Inflammatory disease    |
| Graves’ disease                                         | graves  | Immune / Inflammatory disease    |
| Type 1 diabetes                                         | T1D     | Immune / Metabolic disease       |
| Asthma                                                  | asthma  | Immune / Respiratory disease     |
| Hemoglobin                                              | HB      | Red blood cell trait             |
| Hemoglobin concentration                                | hgb     | Red blood cell trait             |
| Hematocrit                                              | HCT     | Red blood cell trait             |
| High light scatter reticulocyte count                   | HLSRetc | Red blood cell trait             |
| High light scatter reticulocyte percentage of red cells | HLSRetp | Red blood cell trait             |
| Immature fraction of reticulocytes                      | IRF     | Red blood cell trait             |
| Mean corpuscular hemoglobin                             | MCH     | Red blood cell trait             |
| Mean corpuscular hemoglobin concentration               | MCHC    | Red blood cell trait             |
| Mean corpuscular volume                                 | MCV     | Red blood cell trait             |
| Mean reticulocyte volume                                | MRV     | Red blood cell trait             |
| Mean spheric corpuscular volume                         | MSCV    | Red blood cell trait             |
| Red blood cell count                                    | RBC     | Red blood cell trait             |
| Red cell distribution width                             | RDW     | Red blood cell trait             |
| Reticulocyte count                                      | RET     | Red blood cell trait             |
| Reticulocyte fraction of red cells                      | RETP    | Red blood cell trait             |
| Plateletcrit                                            | PCT     | Platelet trait                   |
| Platelet distribution width                             | PDW     | Platelet trait                   |
| Platelet count                                          | PLT     | Platelet trait                   |
| Mean platelet volume                                    | MPV     | Platelet trait                   |
| White blood cell count                                  | WBC     | White blood cell trait           |
| Basophil count                                          | basoc   | White blood cell trait           |
| Basophil percentage of white cells                      | basop   | White blood cell trait           |
| Eosinophil count                                        | eosc    | White blood cell trait           |
| Eosinophil percentage of white cells                    | epsp    | White blood cell trait           |
| Lymphocyte count                                        | lymphc  | White blood cell trait           |
| Lymphocyte percentage of white cells                    | lymphp  | White blood cell trait           |
| Monocyte count                                          | mono    | White blood cell trait           |
| Monocyte percentage of white cells                      | monop   | White blood cell trait           |
| Neutrophil count                                        | neutc   | White blood cell trait           |
| Neutrophil percentage of white cells                    | neutp   | White blood cell trait           |
| Granulocyte count                                       | gran    | White blood cell trait           |
| Low-density lipoprotein cholesterol                     | LDL     | Lipid / Metabolic trait          |
| Body mass index                                         | BMI     | Metabolic / Anthropometric trait |

```{r}
celltypes <- c("B_cell","CD14_positive_monocyte","CD15_positive_leukocyte","platelet","T_cell","thymocyte")
type <- c("B cell (CD19+)","Monocyte (CD14+)","Leukocyte (CD15+)","Platelet","T cell (CD4+)","T cell (CD8+)")
names(type) <- celltypes

source("/project/xinhe/xsun/pathway_factor/data_v2/traits.R")


folder_IV <- "/project/xinhe/xsun/pathway_factor/data_v2/indep_loci/"


df <- c()
for (trait in traits_old){
  
  file_IV <- paste0(folder_IV,trait,"_prunedsnps.txt")
  
  if(!file.exists(file_IV)) next
  
  snps <- read.table(file_IV, header = T)
  
  tmp <- c(trait, nrow(snps))
  df <- rbind(df,tmp)
}

df <- as.data.frame(df)
rownames(df) <- NULL

colnames(df) <- c("Trait","#of SNPs")

 DT::datatable(df,caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Old GWAS traits'),options = list(pageLength = 10) )
 
 
df <- c()
for (trait in traits_newbatch){
  
  file_IV <- paste0(folder_IV,trait,"_prunedsnps.txt")
  
  if(!file.exists(file_IV)) next
  
  snps <- read.table(file_IV, header = T)
  
  tmp <- c(trait, nrow(snps))
  df <- rbind(df,tmp)
}

df <- as.data.frame(df)
rownames(df) <- NULL

colnames(df) <- c("Trait","#of SNPs")

DT::datatable(df,caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','New GWAS traits -- EUR'),options = list(pageLength = 10) )



df <- c()
for (trait in traits_EAS){
  
  file_IV <- paste0(folder_IV,trait,"_prunedsnps.txt")
  
  if(!file.exists(file_IV)) next
  
  snps <- read.table(file_IV, header = T)
  
  tmp <- c(trait, nrow(snps))
  df <- rbind(df,tmp)
}

df <- as.data.frame(df)
rownames(df) <- NULL

colnames(df) <- c("Trait","#of SNPs")

DT::datatable(df,caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','New GWAS traits -- EAS'),options = list(pageLength = 10) )

```

