---
title: "ACAT for specific pairs"
author: "XSun"
date: "2025-11-15"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
---

# Introduction

We examine top pairs with low noMHC_trait_null p-values here, as well as some interesting pairs. 

```{r warning=F, message=F}
library(ggplot2)
library(gridExtra)

celltypes <- c("B_cell","CD14_positive_monocyte","CD15_positive_leukocyte","platelet","T_cell","thymocyte")
types <- c("B cell (CD19+)","Monocyte (CD14+)","Granulocyte (CD15+)","Platelet","T cell (CD4+)","T cell (CD8+)")
names(celltypes) <- types
names(types) <- celltypes

qqplot <- function(pvalues,title=NULL) {
  
  pval <- pvalues[complete.cases(pvalues)]
  title <- title
  plotdata <- data.frame(observed = -log10(sort(as.numeric(pval))),
                         expected = -log10(ppoints(length(pval))))
  
  qq <- ggplot(plotdata) + theme_bw(base_line_size =0.3) +
    geom_point(aes(expected, observed), shape = 1, size = 1.5,color = "steelblue") +
    geom_abline(intercept = 0, slope = 1, alpha = 0.6, color = "red") +
    ggtitle(title) + theme(plot.title = element_text(hjust = 0.5)) +
    labs(x = expression(paste("Expected -log"[10],"(p-value)")),
         y = expression(paste("Observed -log"[10],"(p-value)"))) +
    
    theme(axis.title.x = element_text(size = 14),
          axis.text.x = element_text(size = 12, color = "black"),
          axis.title.y = element_text(size = 14),
          axis.text.y = element_text(size = 12, color = "black") )
  
  return(qq)
  
}

DT::datatable(matrix())
```


# Top 5 pairs for each cell type

```{r fig.height=3, fig.width=3, warning=F, message=F, results='asis'}

for (celltype in celltypes[1]){
  
  cat(celltype)
  cat("<br>")
  cat("<br>")
  
  file <- paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/ECT_summary_final/",celltype,"_ECT_summary_EUR_SLEremoved_noMHCadded.RDS")
  acat_celltype <- readRDS(file)
  acat_celltype <- acat_celltype[order(acat_celltype$acat_p_correct_noMHC_traitnull),]
  
  acat_top5 <- acat_celltype[1:5,]
  
  for (i in 1:nrow(acat_top5)){
    
    cat(paste0("Top", i,"\n"))
    
    trait <- acat_top5$trait[i]
    factor <- acat_top5$factor[i]
    
    df <- readRDS(paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/ECT_summary_final/", celltype,"_ECT_summary_EUR_SLEremoved_noMHCadded.RDS"))
    df$celltype <- types[df$celltype]
    cat(knitr::knit_print(DT::datatable(df[df$trait == trait & df$factor == factor,], caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Pair details',options = list(pageLength = 10)))))
    cat("<br>")
    cat("<br>")
    cat("<br>")
    cat("<br>")
    
    file_harmo <- paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/assoc_harmonize/",celltype, "-", trait, "_harmo.RDS")
    dt_harmo <- readRDS(file_harmo)
    
    dat <- dt_harmo[[factor]]
    
    p <- qqplot(dat$pval.exposure, title = "p-values from \nfactor association test")
    print(p)
    
    file_detail <- paste0("/project/xinhe/xsun/pathway_factor/analysis/2.ACAT_v2/results/acat_snpdetail_noMHCtraitnull/",celltype, "_", factor,"_", trait,".RDS")
    dat_suppsnp <- readRDS(file_detail)
    cat(knitr::knit_print(DT::datatable(dat_suppsnp, caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Supporting SNPs',options = list(pageLength = 5)))))
    
    cat("<br>")
    cat("<br>")
    cat("<br>")
    cat("<br>")
    cat("<br>")
    cat("<br>")
    
  }
  
}




```


# Some other interesting examples 

# Platelet

## Platelet - Hippo signaling pathway - RET-ebi-a-GCST90002405

```{r fig.height=3, fig.width=3, warning=F, message=F, results='asis'}

celltype <- "platelet"
trait <- "RET-ebi-a-GCST90002405"
factor <- "04390_PC5"
fdr_cutoff <- 0.2

file_harmo <- paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/assoc_harmonize/",celltype, "-", trait, "_harmo.RDS")
dt_harmo <- readRDS(file_harmo)

df <- readRDS(paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/ECT_summary_final/", celltype,"_ECT_summary_EUR_SLEremoved_noMHCadded.RDS"))

df$celltype <- types[df$celltype]

DT::datatable(df[df$trait == trait & df$factor == factor,],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Details for this pair'),options = list(pageLength = 10) )

dat <- dt_harmo[[factor]]

qqplot(dat$pval.exposure, title = "p-values from \nfactor association test")

DT::datatable(dat[dat$FDR.exposure < 0.2,c("SNP","chr.exposure","pos.exposure","pval.outcome", "pval.exposure","FDR.exposure")],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Supporting SNPs'),options = list(pageLength = 10) )

```







<!-- # B cell -->

<!-- ## B cell - ECM-receptor interaction - T1D-ebi-a-GCST90014023 -->

<!-- ```{r fig.height=3, fig.width=3, warning=F, message=F, results='asis'} -->

<!-- celltype <- "B_cell" -->
<!-- trait <- "T1D-ebi-a-GCST90014023" -->
<!-- factor <- "04512_PC1" -->
<!-- fdr_cutoff <- 0.2 -->

<!-- file_harmo <- paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/assoc_harmonize/",celltype, "-", trait, "_harmo.RDS") -->
<!-- dt_harmo <- readRDS(file_harmo) -->

<!-- df <- readRDS(paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/ECT_summary_final/", celltype,"_ECT_summary_EUR_SLEremoved_noMHCadded.RDS")) -->

<!-- df$celltype <- types[df$celltype] -->

<!-- DT::datatable(df[df$trait == trait & df$factor == factor,],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Details for this pair'),options = list(pageLength = 10) ) -->

<!-- dat <- dt_harmo[[factor]] -->

<!-- qqplot(dat$pval.exposure, title = "p-values from \nfactor association test") -->

<!-- DT::datatable(dat[dat$FDR.exposure < 0.2,c("SNP","chr.exposure","pos.exposure","pval.outcome", "pval.exposure","FDR.exposure")],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Supporting SNPs'),options = list(pageLength = 10) ) -->

<!-- ``` -->




<!-- # Monocyte (CD14+) -->

<!-- ## Monocyte (CD14+) - Protein processing in endoplasmic reticulum - WBC-ebi-a-GCST90002407 -->

<!-- ```{r fig.height=3, fig.width=3, warning=F, message=F, results='asis'} -->

<!-- celltype <- "CD14_positive_monocyte" -->
<!-- trait <- "WBC-ebi-a-GCST90002407" -->
<!-- factor <- "04141_PC1" -->
<!-- fdr_cutoff <- 0.2 -->

<!-- file_harmo <- paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/assoc_harmonize/",celltype, "-", trait, "_harmo.RDS") -->
<!-- dt_harmo <- readRDS(file_harmo) -->

<!-- df <- readRDS(paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/ECT_summary_final/", celltype,"_ECT_summary_EUR_SLEremoved_noMHCadded.RDS")) -->

<!-- df$celltype <- types[df$celltype] -->

<!-- DT::datatable(df[df$trait == trait & df$factor == factor,],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Details for this pair'),options = list(pageLength = 10) ) -->

<!-- dat <- dt_harmo[[factor]] -->

<!-- qqplot(dat$pval.exposure, title = "p-values from \nfactor association test") -->

<!-- DT::datatable(dat[dat$FDR.exposure < 0.2,c("SNP","chr.exposure","pos.exposure","pval.outcome", "pval.exposure","FDR.exposure")],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Supporting SNPs'),options = list(pageLength = 10) ) -->

<!-- ``` -->


<!-- ## Monocyte (CD14+) - Amino sugar and nucleotide sugar metabolism - WBC-ebi-a-GCST90002407 -->

<!-- ```{r fig.height=3, fig.width=3, warning=F, message=F, results='asis'} -->

<!-- celltype <- "CD14_positive_monocyte" -->
<!-- trait <- "WBC-ebi-a-GCST90002407" -->
<!-- factor <- "00520_PC1" -->
<!-- fdr_cutoff <- 0.2 -->

<!-- file_harmo <- paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/assoc_harmonize/",celltype, "-", trait, "_harmo.RDS") -->
<!-- dt_harmo <- readRDS(file_harmo) -->

<!-- df <- readRDS(paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/ECT_summary_final/", celltype,"_ECT_summary_EUR_SLEremoved_noMHCadded.RDS")) -->

<!-- df$celltype <- types[df$celltype] -->

<!-- DT::datatable(df[df$trait == trait & df$factor == factor,],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Details for this pair'),options = list(pageLength = 10) ) -->

<!-- dat <- dt_harmo[[factor]] -->

<!-- qqplot(dat$pval.exposure, title = "p-values from \nfactor association test") -->

<!-- DT::datatable(dat[dat$FDR.exposure < 0.2,c("SNP","chr.exposure","pos.exposure","pval.outcome", "pval.exposure","FDR.exposure")],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Supporting SNPs'),options = list(pageLength = 10) ) -->

<!-- ``` -->


<!-- ## Monocyte (CD14+) - Cholesterol metabolism - WBC-ebi-a-GCST90002407 -->

<!-- ```{r fig.height=3, fig.width=3, warning=F, message=F, results='asis'} -->

<!-- celltype <- "CD14_positive_monocyte" -->
<!-- trait <- "WBC-ebi-a-GCST90002407" -->
<!-- factor <- "04979_PC1" -->
<!-- fdr_cutoff <- 0.2 -->

<!-- file_harmo <- paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/assoc_harmonize/",celltype, "-", trait, "_harmo.RDS") -->
<!-- dt_harmo <- readRDS(file_harmo) -->

<!-- df <- readRDS(paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/ECT_summary_final/", celltype,"_ECT_summary_EUR_SLEremoved_noMHCadded.RDS")) -->

<!-- df$celltype <- types[df$celltype] -->

<!-- DT::datatable(df[df$trait == trait & df$factor == factor,],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Details for this pair'),options = list(pageLength = 10) ) -->

<!-- dat <- dt_harmo[[factor]] -->

<!-- qqplot(dat$pval.exposure, title = "p-values from \nfactor association test") -->

<!-- DT::datatable(dat[dat$FDR.exposure < 0.2,c("SNP","chr.exposure","pos.exposure","pval.outcome", "pval.exposure","FDR.exposure")],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Supporting SNPs'),options = list(pageLength = 10) ) -->

<!-- ``` -->






<!-- # Granulocyte (CD15+) -->

<!-- ## Granulocyte (CD15+) - Glutathione metabolism - PLT-ebi-a-GCST90002402 -->

<!-- ```{r fig.height=3, fig.width=3, warning=F, message=F, results='asis'} -->

<!-- celltype <- "CD15_positive_leukocyte" -->
<!-- trait <- "PLT-ebi-a-GCST90002402" -->
<!-- factor <- "00480_PC4" -->
<!-- fdr_cutoff <- 0.2 -->

<!-- file_harmo <- paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/assoc_harmonize/",celltype, "-", trait, "_harmo.RDS") -->
<!-- dt_harmo <- readRDS(file_harmo) -->

<!-- df <- readRDS(paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/ECT_summary_final/", celltype,"_ECT_summary_EUR_SLEremoved_noMHCadded.RDS")) -->

<!-- df$celltype <- types[df$celltype] -->

<!-- DT::datatable(df[df$trait == trait & df$factor == factor,],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Details for this pair'),options = list(pageLength = 10) ) -->

<!-- dat <- dt_harmo[[factor]] -->

<!-- qqplot(dat$pval.exposure, title = "p-values from \nfactor association test") -->

<!-- DT::datatable(dat[dat$FDR.exposure < 0.2,c("SNP","chr.exposure","pos.exposure","pval.outcome", "pval.exposure","FDR.exposure")],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Supporting SNPs'),options = list(pageLength = 10) ) -->

<!-- ``` -->


<!-- ## Granulocyte (CD15+) - Complement and coagulation cascades - MPV-ebi-a-GCST90002395 -->

<!-- ```{r fig.height=3, fig.width=3, warning=F, message=F, results='asis'} -->

<!-- celltype <- "CD15_positive_leukocyte" -->
<!-- trait <- "MPV-ebi-a-GCST90002395" -->
<!-- factor <- "04610_PC3" -->
<!-- fdr_cutoff <- 0.2 -->

<!-- file_harmo <- paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/assoc_harmonize/",celltype, "-", trait, "_harmo.RDS") -->
<!-- dt_harmo <- readRDS(file_harmo) -->

<!-- df <- readRDS(paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/ECT_summary_final/", celltype,"_ECT_summary_EUR_SLEremoved_noMHCadded.RDS")) -->

<!-- df$celltype <- types[df$celltype] -->

<!-- DT::datatable(df[df$trait == trait & df$factor == factor,],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Details for this pair'),options = list(pageLength = 10) ) -->

<!-- dat <- dt_harmo[[factor]] -->

<!-- qqplot(dat$pval.exposure, title = "p-values from \nfactor association test") -->

<!-- DT::datatable(dat[dat$FDR.exposure < 0.2,c("SNP","chr.exposure","pos.exposure","pval.outcome", "pval.exposure","FDR.exposure")],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Supporting SNPs'),options = list(pageLength = 10) ) -->

<!-- ``` -->








<!-- # T cell (CD4+) -->

<!-- ## T cell (CD4+) - Inositol phosphate metabolism - WBC-ebi-a-GCST90002407 -->

<!-- ```{r fig.height=3, fig.width=3, warning=F, message=F, results='asis'} -->

<!-- celltype <- "T_cell" -->
<!-- trait <- "WBC-ebi-a-GCST90002407" -->
<!-- factor <- "00562_PC5" -->
<!-- fdr_cutoff <- 0.2 -->

<!-- file_harmo <- paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/assoc_harmonize/",celltype, "-", trait, "_harmo.RDS") -->
<!-- dt_harmo <- readRDS(file_harmo) -->

<!-- df <- readRDS(paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/ECT_summary_final/", celltype,"_ECT_summary_EUR_SLEremoved_noMHCadded.RDS")) -->

<!-- df$celltype <- types[df$celltype] -->

<!-- DT::datatable(df[df$trait == trait & df$factor == factor,],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Details for this pair'),options = list(pageLength = 10) ) -->

<!-- dat <- dt_harmo[[factor]] -->

<!-- qqplot(dat$pval.exposure, title = "p-values from \nfactor association test") -->

<!-- DT::datatable(dat[dat$FDR.exposure < 0.2,c("SNP","chr.exposure","pos.exposure","pval.outcome", "pval.exposure","FDR.exposure")],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Supporting SNPs'),options = list(pageLength = 10) ) -->

<!-- ``` -->


<!-- ## T cell (CD4+) - Pyrimidine metabolism - PLT-ebi-a-GCST90002402 -->

<!-- ```{r fig.height=3, fig.width=3, warning=F, message=F, results='asis'} -->

<!-- celltype <- "T_cell" -->
<!-- trait <- "PLT-ebi-a-GCST90002402" -->
<!-- factor <- "00240_PC4" -->
<!-- fdr_cutoff <- 0.2 -->

<!-- file_harmo <- paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/assoc_harmonize/",celltype, "-", trait, "_harmo.RDS") -->
<!-- dt_harmo <- readRDS(file_harmo) -->

<!-- df <- readRDS(paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/ECT_summary_final/", celltype,"_ECT_summary_EUR_SLEremoved_noMHCadded.RDS")) -->

<!-- df$celltype <- types[df$celltype] -->

<!-- DT::datatable(df[df$trait == trait & df$factor == factor,],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Details for this pair'),options = list(pageLength = 10) ) -->

<!-- dat <- dt_harmo[[factor]] -->

<!-- qqplot(dat$pval.exposure, title = "p-values from \nfactor association test") -->

<!-- DT::datatable(dat[dat$FDR.exposure < 0.2,c("SNP","chr.exposure","pos.exposure","pval.outcome", "pval.exposure","FDR.exposure")],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Supporting SNPs'),options = list(pageLength = 10) ) -->

<!-- ``` -->


<!-- # T cell (CD8+) -->

<!-- ## T cell (CD8+) - Glutamatergic synapse - AS-finn-b-M13_ANKYLOSPON -->

<!-- ```{r fig.height=3, fig.width=3, warning=F, message=F, results='asis'} -->

<!-- celltype <- "thymocyte" -->
<!-- trait <- "AS-finn-b-M13_ANKYLOSPON" -->
<!-- factor <- "04724_PC5" -->
<!-- fdr_cutoff <- 0.2 -->

<!-- file_harmo <- paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/assoc_harmonize/",celltype, "-", trait, "_harmo.RDS") -->
<!-- dt_harmo <- readRDS(file_harmo) -->

<!-- df <- readRDS(paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/ECT_summary_final/", celltype,"_ECT_summary_EUR_SLEremoved_noMHCadded.RDS")) -->

<!-- df$celltype <- types[df$celltype] -->

<!-- DT::datatable(df[df$trait == trait & df$factor == factor,],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Details for this pair'),options = list(pageLength = 10) ) -->

<!-- dat <- dt_harmo[[factor]] -->

<!-- qqplot(dat$pval.exposure, title = "p-values from \nfactor association test") -->

<!-- DT::datatable(dat[dat$FDR.exposure < 0.2,c("SNP","chr.exposure","pos.exposure","pval.outcome", "pval.exposure","FDR.exposure")],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Supporting SNPs'),options = list(pageLength = 10) ) -->

<!-- ``` -->





<!-- ## T cell (CD8+) - Cholesterol metabolism - lymphc-ebi-a-GCST90002388 -->

<!-- ```{r fig.height=3, fig.width=3, warning=F, message=F, results='asis'} -->

<!-- celltype <- "thymocyte" -->
<!-- trait <- "lymphc-ebi-a-GCST90002388" -->
<!-- factor <- "04979_PC5" -->
<!-- fdr_cutoff <- 0.2 -->

<!-- file_harmo <- paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/assoc_harmonize/",celltype, "-", trait, "_harmo.RDS") -->
<!-- dt_harmo <- readRDS(file_harmo) -->

<!-- df <- readRDS(paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/ECT_summary_final/", celltype,"_ECT_summary_EUR_SLEremoved_noMHCadded.RDS")) -->

<!-- df$celltype <- types[df$celltype] -->

<!-- DT::datatable(df[df$trait == trait & df$factor == factor,],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Details for this pair'),options = list(pageLength = 10) ) -->

<!-- dat <- dt_harmo[[factor]] -->

<!-- qqplot(dat$pval.exposure, title = "p-values from \nfactor association test") -->

<!-- DT::datatable(dat[dat$FDR.exposure < 0.2,c("SNP","chr.exposure","pos.exposure","pval.outcome", "pval.exposure","FDR.exposure")],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Supporting SNPs'),options = list(pageLength = 10) ) -->

<!-- ``` -->







<!-- ## T cell (CD8+) - TGF-beta signaling pathway - AS-finn-b-M13_ANKYLOSPON -->

<!-- ```{r fig.height=3, fig.width=3, warning=F, message=F, results='asis'} -->

<!-- celltype <- "thymocyte" -->
<!-- trait <- "AS-finn-b-M13_ANKYLOSPON" -->
<!-- factor <- "04350_PC1" -->
<!-- fdr_cutoff <- 0.2 -->

<!-- file_harmo <- paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/assoc_harmonize/",celltype, "-", trait, "_harmo.RDS") -->
<!-- dt_harmo <- readRDS(file_harmo) -->

<!-- df <- readRDS(paste0("/project/xinhe/xsun/pathway_factor/analysis/1.ECT_v2/ECT_summary_final/", celltype,"_ECT_summary_EUR_SLEremoved_noMHCadded.RDS")) -->

<!-- df$celltype <- types[df$celltype] -->

<!-- DT::datatable(df[df$trait == trait & df$factor == factor,],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Details for this pair'),options = list(pageLength = 10) ) -->

<!-- dat <- dt_harmo[[factor]] -->

<!-- qqplot(dat$pval.exposure, title = "p-values from \nfactor association test") -->

<!-- DT::datatable(dat[dat$FDR.exposure < 0.2,c("SNP","chr.exposure","pos.exposure","pval.outcome", "pval.exposure","FDR.exposure")],caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Supporting SNPs'),options = list(pageLength = 10) ) -->

<!-- ``` -->



